# version: '3.6'

# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.2.0
#     hostname: zookeeper
#     container_name: zookeeper
#     ports:
#       - '2181:2181'
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000

#   broker1:
#     image: confluentinc/cp-kafka:7.2.0
#     hostname: broker1
#     container_name: broker1
#     depends_on:
#       - zookeeper
#     ports:
#       - '9092:9092'
#       - '19092:19092'
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://broker1:9092,EXTERNAL://broker1:19092
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092,EXTERNAL:35.240.239.52:19092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#       CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
#       CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:29092
#       CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
#       CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2 # Set replication for metrics topic


#   broker2:
#     image: confluentinc/cp-kafka:7.2.0
#     hostname: broker2
#     container_name: broker2
#     depends_on:
#       - zookeeper
#     ports:
#       - '9093:9093'
#       - '19093:19093'
#     environment:
#       KAFKA_BROKER_ID: 2
#       KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_LISTENERS: PLAINTEXT://broker2:29093,PLAINTEXT_HOST://broker2:9093,EXTERNAL://broker2:19093
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:29093,PLAINTEXT_HOST://localhost:9093,EXTERNAL://35.240.239.52:19093
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
#       KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#       KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
#       KAFKA_DEFAULT_REPLICATION_FACTOR: 2
#       KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 2
#       KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#       CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
#       CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker2:29093
#       CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
#       CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2 # Set replication for metrics topic


#   schema-registry:
#     image: confluentinc/cp-schema-registry:7.2.0
#     hostname: schema-registry
#     container_name: schema-registry
#     depends_on:
#       - zookeeper
#       - broker1
#       - broker2
#     ports:
#       - "8081:8081"
#     environment:
#       SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker1:29092,broker2:29093"
#       SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
#       SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081


#   control-center:
#     image: confluentinc/cp-enterprise-control-center:7.2.0
#     hostname: control-center
#     container_name: control-center
#     depends_on:
#       - zookeeper
#       - broker1
#       - broker2
#       - schema-registry
#     ports:
#       - "9021:9021"
#     environment:
#       CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker1:29092,broker2:29093'
#       CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#       CONTROL_CENTER_SCHEMA_REGISTRY_URL: "schema-registry:8081"
#       CONTROL_CENTER_REPLICATION_FACTOR: 2
#       CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 2
#       CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 2
#       CONFLUENT_METRICS_TOPIC_REPLICATION: 2
#       PORT: 9021

#   kafka-rest:
#     image: confluentinc/cp-kafka-rest:7.2.0
#     hostname: kafka-rest
#     ports:
#       - "8082:8082"
#     depends_on:
#       - zookeeper
#       - schema-registry
#       - broker1
#       - broker2
#     environment:
#       KAFKA_REST_BOOTSTRAP_SERVERS: 'broker1:29092,broker2:29093'
#       KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#       KAFKA_REST_SCHEMA_REGISTRY_URL: 'schema-registry:8081'
#       KAFKA_REST_HOST_NAME: 'kafka-rest'
#       KAFKA_REST_LISTENERS: 'kafka-rest:8082'


version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"


  kafka-1:
    image: confluentinc/cp-kafka:7.2.0
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://35.240.239.52:9092,DOCKER://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper

  kafka-2:
    image: confluentinc/cp-kafka:7.2.0
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19093,EXTERNAL://35.240.239.52:9093,DOCKER://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 2
    depends_on:
      - zookeeper

  kafka-3:
    image: confluentinc/cp-kafka:7.2.0
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:19094,EXTERNAL://35.240.239.52:9094,DOCKER://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 3
    depends_on:
      - zookeeper
  